const fs = require('fs');
let file = 'src/main/java/modularcontents/custom/client/ModularResourcePack.java';
let content = fs.readFileSync(file, 'utf8');

const targetBlockstate = `                } else if ("horizontal".equalsIgnoreCase(info.rotationType)) {
                    generatedJson = "{\n  \\"variants\\": {\n    \\"facing=north\\": { \\"model\\": \\"modularcontents:" + blockId + "\\" },\n    \\"facing=east\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"y\\": 90 },\n    \\"facing=south\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"y\\": 180 },\n    \\"facing=west\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"y\\": 270 }\n  }\n}";`;

const newBlockstates = `                } else if (type.equals("button")) {
                    generatedJson = "{\n  \\"variants\\": {\n    \\"facing=up,powered=false\\": { \\"model\\": \\"modularcontents:" + blockId + "\\" },\n    \\"facing=up,powered=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_pressed\\" },\n    \\"facing=down,powered=false\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"x\\": 180 },\n    \\"facing=down,powered=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_pressed\\", \\"x\\": 180 },\n    \\"facing=east,powered=false\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"x\\": 90, \\"y\\": 90 },\n    \\"facing=east,powered=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_pressed\\", \\"x\\": 90, \\"y\\": 90 },\n    \\"facing=west,powered=false\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"x\\": 90, \\"y\\": 270 },\n    \\"facing=west,powered=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_pressed\\", \\"x\\": 90, \\"y\\": 270 },\n    \\"facing=south,powered=false\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"x\\": 90, \\"y\\": 180 },\n    \\"facing=south,powered=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_pressed\\", \\"x\\": 90, \\"y\\": 180 },\n    \\"facing=north,powered=false\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"x\\": 90 },\n    \\"facing=north,powered=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_pressed\\", \\"x\\": 90 }\n  }\n}";
                } else if (type.equals("pressure_plate")) {
                    generatedJson = "{\n  \\"variants\\": {\n    \\"powered=false\\": { \\"model\\": \\"modularcontents:" + blockId + "\\" },\n    \\"powered=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_down\\" }\n  }\n}";
                } else if (type.equals("trapdoor")) {
                    generatedJson = "{\n  \\"variants\\": {\n    \\"facing=north,half=bottom,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_bottom\\" },\n    \\"facing=south,half=bottom,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_bottom\\", \\"y\\": 180 },\n    \\"facing=east,half=bottom,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_bottom\\", \\"y\\": 90 },\n    \\"facing=west,half=bottom,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_bottom\\", \\"y\\": 270 },\n    \\"facing=north,half=top,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_top\\" },\n    \\"facing=south,half=top,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_top\\", \\"y\\": 180 },\n    \\"facing=east,half=top,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_top\\", \\"y\\": 90 },\n    \\"facing=west,half=top,open=false\\": { \\"model\\": \\"modularcontents:" + blockId + "_top\\", \\"y\\": 270 },\n    \\"facing=north,half=bottom,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\" },\n    \\"facing=south,half=bottom,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\", \\"y\\": 180 },\n    \\"facing=east,half=bottom,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\", \\"y\\": 90 },\n    \\"facing=west,half=bottom,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\", \\"y\\": 270 },\n    \\"facing=north,half=top,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\", \\"x\\": 180, \\"y\\": 180 },\n    \\"facing=south,half=top,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\", \\"x\\": 180, \\"y\\": 0 },\n    \\"facing=east,half=top,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\", \\"x\\": 180, \\"y\\": 270 },\n    \\"facing=west,half=top,open=true\\": { \\"model\\": \\"modularcontents:" + blockId + "_open\\", \\"x\\": 180, \\"y\\": 90 }\n  }\n}";
                } else if ("horizontal".equalsIgnoreCase(info.rotationType)) {
                    generatedJson = "{\n  \\"variants\\": {\n    \\"facing=north\\": { \\"model\\": \\"modularcontents:" + blockId + "\\" },\n    \\"facing=east\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"y\\": 90 },\n    \\"facing=south\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"y\\": 180 },\n    \\"facing=west\\": { \\"model\\": \\"modularcontents:" + blockId + "\\", \\"y\\": 270 }\n  }\n}";`;

content = content.replace(targetBlockstate, newBlockstates);
fs.writeFileSync(file, content);
console.log("Patched blockstates");
